#!/usr/bin/env bash
# Generated by `babello --generate-hook-warn` / `babello --generate-hook-block`.
# Checks the commit message for spelling/grammar issues via DeepL's Write API
# (through the babello CLI) and suggests, or enforces, a corrected version.
set -euo pipefail

COMMIT_MSG_FILE="$1"

MESSAGE="$(grep -v '^#' "$COMMIT_MSG_FILE" | sed -e '/^[[:space:]]*$/d')"

if [[ -z "$MESSAGE" ]]; then
  exit 0
fi

if [[ -z "${DEEPL_API_KEY:-}" ]]; then
  echo "commit-msg: DEEPL_API_KEY not set, skipping spelling/grammar check" >&2
  exit 0
fi

if ! command -v babello >/dev/null 2>&1; then
  echo "commit-msg: babello not found on PATH, skipping spelling/grammar check" >&2
  exit 0
fi

OUTPUT="$(babello --improve --to __BABELLO_TO__ "$MESSAGE")" || {
  echo "commit-msg: babello check failed, skipping" >&2
  exit 0
}

CORRECTED="${OUTPUT#*" -> "}"

if [[ -n "$CORRECTED" && "$CORRECTED" != "$MESSAGE" ]]; then
  echo ""
  echo "babello: possible spelling/grammar issue in your commit message"
  echo "  original:  $MESSAGE"
  echo "  suggested: $CORRECTED"
  echo ""
  exit __BABELLO_EXIT_ON_ISSUE__
fi

exit 0
